all logic
vanyaio/raketa-backend pull request #1
Opened 2023-04-17 14:19 UTC by Edbeer

Basis logic

2023-04-19 09:07 UTC, vanyaio commented on Makefile
> +docker:
Давай postgres-up или что-то в этом духе, просто docker-* здесь и далее непонятно.
Зачем docker-start нужен? Кажется docker-exec хватило бы?
Добавь еще плз цель с удалением контейнера

2023-04-19 09:07 UTC, vanyaio commented on internal/service/service.go
> +	botpb.UnimplementedBotServiceServer
Это пакет service. Уровень сервис не должен ничего знать про grpc или любой другой транспорт.
Переименуй этот пакет и все упоминания про сервис в по вкусу api/handlers/endpoints/...

2023-04-19 09:07 UTC, vanyaio commented on internal/service/service.go
> +type IStorage interface {
Вряд ли куда-то экспортироваться будет, можно просто storage

2023-04-19 09:07 UTC, vanyaio commented on internal/service/service.go
> +
Убери плз пустые строки в начале функции, немного странный кодстайл

2023-04-19 09:07 UTC, vanyaio commented on internal/storage/storage.go
> +	botpb "github.com/vanyaio/raketa-backend/proto"
уровень storage ничего не должен знать про grpc. Вход во все функции должен быть types.*

2023-04-19 09:07 UTC, vanyaio commented on internal/storage/storage.go
> +	ctx = context.TODO()
Зачем здесь и далее context.TODO()?

2023-04-19 09:07 UTC, vanyaio commented on internal/storage/storage.go
> +	if err := s.db.QueryRow(ctx, query, user.ID).Scan(&u.ID); err != nil {
Зачем returning? Насколько понимаю из-за прото файла - к нему есть вопросы ниже

2023-04-19 09:07 UTC, vanyaio commented on proto/bot.proto
> +    // SignUp user
Лишний коммент

2023-04-19 09:07 UTC, vanyaio commented on proto/bot.proto
> +            post: "/sign-up"
Давай /users/sign-up

2023-04-19 09:07 UTC, vanyaio commented on proto/bot.proto
> +            post: "/create"
Давай здесь и далее /tasks/*

2023-04-19 09:07 UTC, vanyaio commented on proto/bot.proto
> +            post: "/create"
Здесь и далее CreateRequest -> CreateTaskRequest, CreateResponse -> CreateTaskResponse

2023-04-19 09:07 UTC, vanyaio commented on proto/bot.proto
> +            post: "/sign-up"
Если начали SignUp, давай консистентно продолжать SignUpRequest, SignUpResponse

2023-04-19 09:07 UTC, vanyaio commented on proto/bot.proto
> +// SignUp request
Избыточные комменты во всем файле

2023-04-19 09:07 UTC, vanyaio commented on proto/bot.proto
> +    // enum Status {
Почему не захотел оставить enum?

2023-04-19 09:07 UTC, vanyaio commented on proto/bot.proto
> +    string url = 1;
Почему не возвращать пустую структуру?

2023-04-19 09:07 UTC, vanyaio commented on proto/bot.proto
> +    string message = 1;
Почему не возвращать пустую структуру?

2023-04-19 09:07 UTC, vanyaio commented on proto/bot.proto
> +    rpc AssignWorker(AssignRequest) returns (AssignResponse) {
Давай Assign ну или AssignUser

2023-04-19 09:07 UTC, vanyaio commented on proto/bot.proto
> +    string message = 1;
Почему не возвращать пустую структуру?

2023-04-19 09:07 UTC, vanyaio commented on proto/bot.proto
> +    string message = 1;
Почему не возвращать пустую структуру?

2023-04-19 09:07 UTC, vanyaio commented on internal/types/types.go
> +	Open     string = "open"
Обычно делают так

```
type Status string

var (
  Open Status = "..."
  ...
)
```

Ну т.е. что-то типа самописных енамов, очень улучшает читаемость кода

2023-04-19 09:07 UTC, vanyaio commented on internal/storage/storage_test.go
> +package storage
Я правильно понял что тут реально база никакая для тестов не нужна, здесь все замокано?
Если да, давай сделаем как говорил настоящий интеграционный тест, чтоб мы реально чекнули, что sql работает. Можно сверху билд тег, например, с названием integration.
Моканный sql я вообще не оч понимаю зачем существует, в проде никогда его не видел

2023-04-19 09:07 UTC, vanyaio commented on main.go
> +	lis, err := net.Listen("tcp", ":50052")
Давай порты, например, через переменную окружения или флаг или еще как-то передать, только не хардкодом

2023-04-20 10:45 UTC, Edbeer commented
Переписал QueryRow на Exec, переписал тесты

2023-04-21 06:09 UTC, vanyaio requested changes

2023-04-21 06:09 UTC, vanyaio commented on internal/service/service.go
> +type BotService struct {
просто Service

2023-04-21 06:09 UTC, vanyaio commented on internal/storage/storage.go
> +	}
defer rows.Close() обязательно всегда надо делать

2023-04-21 06:09 UTC, vanyaio commented on internal/storage/storage.go
> +	}
https://go.dev/doc/tutorial/database-access:

>Defer closing rows so that any resources it holds will be released when the function exits.

2023-04-21 06:09 UTC, vanyaio commented on internal/storage/storage.go
> +	}
Проверяем на ошибки всегда в конце
```
	if err := rows.Err(); err != nil {
		return nil, err
	}
```

https://go.dev/doc/tutorial/database-access:
>After the loop, check for an error from the overall query, using rows.Err. Note that if the query itself fails, checking for an error here is the only way to find out that the results are incomplete.

2023-04-21 06:09 UTC, vanyaio commented on internal/types/types.go
> +	Open     Status = "open"
```
	Closed      Status    = "closed"
	Declined      Status  = "declined"
```

2023-04-21 06:09 UTC, vanyaio commented on internal/service/service.go
> +	case "open":
Юзаем types.Open здесь и далее

2023-04-21 06:09 UTC, vanyaio commented on internal/service/service.go
> +	default:
давай явно `case types.Declined`, в дефолте можно было бы возвращать ошибку мол unknown status, но пока забьем

2023-04-21 06:09 UTC, vanyaio commented on internal/service/service.go
> +			tasksProto = append(tasksProto, taskProto)
Много дублирований кода, давай так
```
	taskProto := &proto.Task{
		Url:    task.Url,
		Status: converStatusToProto(task.Status),
	}
	if task.UserID != nil {
		taskProto.UserId = *task.UserId
	}
	tasksProto = append(tasksProto, taskProto)
```

2023-04-21 06:09 UTC, vanyaio commented on internal/storage/storage_test.go
> +	// db conn
избыточный коммент

2023-04-21 06:09 UTC, vanyaio commented on internal/storage/storage_test.go
> +	require.NoError(t, err)
Здесь и далее избыточно еще раз делать require.NoError, оно внутри и так делается на то же самое значение ошибки. Ну т.е. функциям не надо ничего возвращать

2023-04-21 06:09 UTC, vanyaio commented on internal/storage/storage_test.go
> +	_, err = storage.db.Exec(ctx, `SELECT * FROM users WHERE id = $1`, u.ID)
Мы должны не просто выполнить select, а еще чекнуть, что он вернул не пустой результат

2023-04-21 06:09 UTC, vanyaio commented on internal/storage/storage_test.go
> +	_, err = storage.db.Exec(ctx, `SELECT * FROM tasks WHERE url = $1`, task.Url)
Аналогично: мы должны не просто выполнить select, а еще чекнуть, что он вернул не пустой результат

2023-04-21 06:09 UTC, vanyaio commented on internal/storage/storage_test.go
> +	query := `SELECT NOT EXISTS (SELECT * FROM tasks WHERE url = $1)`
Вот здесь норм - реально проверили, что удаление произошло

2023-04-21 06:09 UTC, vanyaio commented on internal/storage/storage_test.go
> +	_, err = storage.db.Exec(ctx, `SELECT * FROM tasks WHERE url = $1 AND assigned_id IS NOT NULL`, task.Url)
Аналогично: мы должны не просто выполнить select, а еще чекнуть, что он вернул не пустой результат

2023-04-21 06:09 UTC, vanyaio commented on internal/storage/storage_test.go
> +	_, err = storage.db.Exec(ctx, `SELECT * FROM tasks WHERE url = $1 AND status = 'closed'`, req.Url)
Аналогично: мы должны не просто выполнить select, а еще чекнуть, что он вернул не пустой результат

2023-04-21 06:09 UTC, vanyaio commented on internal/storage/storage_test.go
> +	_, err = storage.db.Exec(ctx, `SELECT status, COUNT(*)
есть `WHERE status = 'open'`, возвращать status избыточно.
Ну и то же - давай прочем и увидим, что результат не пуст.

2023-04-21 06:09 UTC, vanyaio commented on main.go
> +	grpcPort := flag.String("gp", ":50052", "grpc server port")
Давай чуть более читаемый нейминг: grpc-port, rest-port

2023-04-21 06:09 UTC, vanyaio commented on main.go
> +	// reflection
избыточные комменты, коммент про порт устарел

2023-04-21 06:10 UTC, vanyaio commented on proto/bot.proto
> +            get: "/tasks/opens"
/tasks/open

2023-04-21 07:43 UTC, vanyaio requested changes

2023-04-21 07:43 UTC, vanyaio commented on internal/storage/storage.go
> +        return nil, err
Отфарматирую плз, в редакторе можно по дефолту поставить чтоб при сохранении файла вызывался go fmt

2023-04-21 07:43 UTC, vanyaio commented on internal/storage/storage_test.go
> +	err = storage.db.QueryRow(ctx, query, u.ID).Scan(&exists)
Ну и здесь и далее проверяем что exists - true. require.True по-моему есть функция

2023-04-21 07:43 UTC, vanyaio commented on internal/storage/storage_test.go
> +	query := `SELECT NOT EXISTS (SELECT * FROM tasks WHERE url = $1)`
Единственное, нужно exists -> notExists и проверить, что оно true

2023-04-21 07:43 UTC, vanyaio commented on internal/storage/storage_test.go
> +	require.Contains(t, tasks, task2)
Давай создадим 3ю таску cо статусом, например, closed по посмотрим, что она не попала в `tasks`: для этого достаточно проверить, что len(tasks) == 2.

2023-04-21 07:43 UTC, vanyaio commented on internal/storage/storage_test.go
> +	query := `SELECT EXISTS (SELECT status, COUNT(*)
Давай выпилим этот запрос на самом деле, нам достаточно просто GetOpenTasks вызвать и посмотреть на его результаты

2023-04-21 08:02 UTC, merged