New functionality
vanyaio/raketa-backend pull request #3
Opened 2023-04-24 07:09 UTC by Edbeer

Реализация методов SetTaskPrice и GetUserRole

2023-04-24 07:12 UTC, Edbeer commented on internal/types/types.go
>  }
Изменение структуры task (+ поле price)

2023-04-24 07:14 UTC, Edbeer commented on internal/service/service.go
> +	})
Перед получением роли идёт проверка, есть ли юзер в бд

2023-04-24 15:57 UTC, vanyaio requested changes

2023-04-24 15:57 UTC, vanyaio commented on migrations/000001_raketadb.up.sql
> +  price bigserial
Сейчас все равно, но дальше новый коммит - новая миграция

2023-04-24 15:57 UTC, vanyaio commented on internal/service/service.go
> +	if ok == false || err != nil {
if !ok

2023-04-24 15:57 UTC, vanyaio commented on internal/storage/storage.go
> +	if exists == false {
!exists

2023-04-25 06:29 UTC, Edbeer commented
ckek -> ckeck

2023-04-25 08:34 UTC, merged